name: Sync Fork with Upstream

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # fetch all history for all branches and tags

    - name: Configure git
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'

    - name: Add upstream remote
      run: git remote add upstream https://github.com/facebookresearch/vggsfm.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout main
        git merge upstream/main
        git push origin main
